### ISSUE TITLE
results when using resnet?

### ISSUE THREAD

**Issue by zhezh** [salesforce/ALBEF#10]
Hi, Thanks for releasing ALBEF, it is a clean and well organized repo.

We use pre-extracted resnet image features with texts for multimodal tasks. I have tried to use ALBEF in our project, but the results is not as expected. I wonder if this is because the resnet image features.

I find that you provide ALBEF with resnet model, could you share any results on downstream tasks when using resnet for images?

**Comment by LiJunnan1992** [comment]
Hi, thanks for your interest.

We haven't fully evaluated ALBEF with resnet. Based on our preliminary smaller-scale experiment, resnet-50 has 1-2% lower performance than a ViT-base16 model. A crucial difference between CNN and ViT is the spatial-granularity of the output features. Since ViT outputs more fine-grained features for each 16x16 patch, it could contain more information for cross-modality interactions.

**Comment by zhezh** [comment]
Thanks @LiJunnan1992 ~
