### ISSUE TITLE
Grad-CAM visualization code

### ISSUE THREAD

**Issue by pqviet** [salesforce/ALBEF#33]
Could you explain the code to extract gradient here?
grads=model.text_encoder.base_model.base_model.encoder.layer[block_num].crossattention.self.get_attn_gradients()
(block_num=8)
Why did you use base_model.base_model here, and what is the connection to "3rd layer of the multimodal heads"?

**Comment by LiJunnan1992** [comment]
base_model is from huggingface implementation to get the actual BertEncoder (please see https://huggingface.co/transformers/v3.0.2/_modules/transformers/modeling_bert.html#BertModel). block_num=8 means the 9th layer of BERT. Since the first 6 layers are used as the text encoder, the 9th layer of BERT becomes the 3rd layer of our multimodal encoder.

**Comment by pqviet** [comment]
Thank you very much. I've learned a lot.
